/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    BackButton: typeof import('./src/components/BackButton.vue')['default']
    Default: typeof import('./src/layouts/default.vue')['default']
    GitHub: typeof import('./src/components/GitHub.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NaiveProvider: typeof import('./src/components/NaiveProvider.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NotivueProvider: typeof import('./src/components/NotivueProvider.vue')['default']
    RouterEntry: typeof import('./src/components/RouterEntry.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    ToggleDarkMode: typeof import('./src/components/ToggleDarkMode.vue')['default']
    ToggleLanguage: typeof import('./src/components/ToggleLanguage.vue')['default']
  }
}
