import {
  active,
  cancel,
  cancelAll,
  channels,
  createChannel,
  Importance,
  isPermissionGranted,
  onAction,
  onNotificationReceived,
  pending,
  registerActionTypes,
  removeActive,
  removeAllActive,
  removeChannel,
  requestPermission,
  Schedule,
  ScheduleEvery,
  sendNotification,
  Visibility,
} from '@tauri-apps/plugin-notification'

export function useTauriNotifications() {
  return {
    Importance,
    Visibility,
    sendNotification,
    requestPermission,
    isPermissionGranted,
    registerActionTypes,
    pending,
    cancel,
    cancelAll,
    active,
    removeActive,
    removeAllActive,
    createChannel,
    removeChannel,
    channels,
    onNotificationReceived,
    onAction,
    Schedule,
    ScheduleEvery,
  }
}
